#!/bin/zsh

ext="sedbak$$"

find . -name project.clj -exec sed -i.$ext "s/\[metosin\/kekkonen\(.*\) \".*\"\]/[metosin\/kekkonen\1 \"$1\"\]/g" '{}' \;
find . -name project.clj -exec sed -i.$ext "s/defproject metosin\/kekkonen\(.*\) \".*\"/defproject metosin\/kekkonen\1 \"$1\"/g" '{}' \;
sed -i.$ext "s/\[metosin\/kekkonen\(.*\) \".*\"\]/[metosin\/kekkonen\1 \"$1\"\]/g" **/*.md
find . -name "*.$ext" -exec rm '{}' \;
